### ISSUE TITLE
Add HTML5 element definitions for HTMLPurifier

### ISSUE THREAD

**Issue by ghost** [vdlp/oc-htmlpurifier-plugin#1]
Enhancement idea: Add HTML5 Elements, see github package: https://github.com/xemlock/htmlpurifier-html5

**Comment by ayumihamsaki** [comment]
Also you could change the config file line of code, found here: https://github.com/vdlp/oc-htmlpurifier-plugin/blob/f49a8588e3b68a3c1c974d8ebc0062591b14e2e8/config/htmlpurifier.php#L186

From:

`'URI.SafeIframeRegexp' => null,`

to this:

`'URI.SafeIframeRegexp' => '%^(https?:)?//(www\.youtube(?:-nocookie)?\.com/embed/|player\.vimeo\.com/video/)%',`

To allow support for youtube and vimeo embeds.
